
modLoader = "javafml" #mandatory
loaderVersion = "${loader_version}" #mandatory
license = "Creative Commons"
issueTrackerURL = "https://github.com/NovaMachina-Mods/TheSculkingWastes/issues" #optional
[[mods]] #mandatory
modId = "sculkingwastes" #mandatory
version = "${version}" #mandatory
displayName = "The Sculking Wastes" #mandatory
displayURL = "" #optional
logoFile = "" #optional
credits = "" #optional
authors = "NovaMachina" #optional
description = """
We opened an ancient door in the dark...
"""
[[dependencies.sculkingwastes]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "${forge_version}" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.sculkingwastes]]
modId = "minecraft"
mandatory = true
versionRange = "${mc_version}"
ordering = "NONE"
side = "BOTH"