blank_issues_enabled: false
contact_links:
  - name: "Discord"
    url: https://discord.gg/CJyAkuw/
    about: Active Discord for updates and discussion
  - name: "Wiki"
    url: https://jacob-williams.me/
    about: "Wiki for The Sculking Wastes"
  - name: "Discussion Board"
    url: https://github.com/NovaMachina-Mods/TheSculkingWastes/discussions
    about: Dissucssions, Q&A, Requests, etc.
  - name: "Issue Board"
    url: https://github.com/NovaMachina-Mods/TheSculkingWastes/issues
    about: All issues and feature requests end up here